<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FC_CONV_M_TO_SUBPX_V2" Id="{fc1692af-45c2-4eee-a342-07c4562babc7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FC_CONV_M_TO_SUBPX_V2 : DINT
(*************************************************************************************************)
(*  FILENAME:    FC_CONV_M_TO_SUBPX_V2                                                           *)
(*  PROJECT:     CALMAR PUPLC                                                                    *)
(*  COPYRIGHT:   All rights reserved (c) Wifag//Polytype, Fribourg/Switzerland (2016)            *)
(*  ENVIRONMENT: TwinCAT PLC                                                                     *)
(*  VERSION:     <version>                                                                       *)
(*************************************************************************************************)
(*  DESCRIPTION:                                                                   <description> *)
(*     This function converts the value from [m] to [subpixel].                                  *)
(*                                                                                </description> *)
(*************************************************************************************************)

VAR_INPUT
  fI_Pos_M         : LREAL;             (*Position or distance in [m]*)
  fI_Res_Ph        : LREAL;             (*Printhead pixel resolution [dpi]*)
  iI_Res_SubPx     : INT;               (*Subpixel pulse resolution [pulse/px]*)
  pI_ConversionErr : POINTER TO UDINT;  (*counts catched data type conversion overflows*)
END_VAR

VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[FC_CONV_M_TO_SUBPX_V2 := FC_LREAL_TO_DINT(((fI_Pos_M * 1_000_000 * fI_Res_Ph * iI_Res_SubPx) / 25400), pI_ConversionErr);]]></ST>
    </Implementation>
    <LineIds Name="FC_CONV_M_TO_SUBPX_V2">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>