<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_ContainerWeu" Id="{fb31222f-8037-4cb6-ae7a-cdb9b6d6ec9b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ContainerWeu EXTENDS FB_ContainerBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ContainerWeu">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>